name: igroove_fan_box_one
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.17+49
publish_to: none

environment:
    sdk: '>=2.12.0 <3.0.0'

module:
    androidX: true

dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter

    http: ^0.13.4

    # SQLite database support for Flutter
    sqflite: ^2.0.2

    flutter_cache_manager: ^3.3.0

    # A comprehensive, cross-platform path manipulation library for Dart.
    path: ^1.8.0

    # Get current device information from within the Flutter application
    device_info: ^2.0.3

    # Provides an API for querying information about an application package.
    package_info: ^2.0.2

    connectivity: ^3.0.6

    # A Flutter plugin for finding commonly used locations on the filesystem.
    path_provider: ^2.0.8

    # Http client for Dart, which supports Interceptors, Global configuration,
    #  FormData, Request Cancellation, File downloading, Timeout etc.

    # this packages geting functionality for opening urls on phone brawser
    url_launcher: ^6.0.18

    # this package for the Date Range Picker
    flutter_date_pickers: ^0.2.9

    # A Flutter plugin for picking images from the image library and camera
    image_picker: ^0.8.4+7

    # audio player package
    audioplayers: ^0.20.1

    # secure storage package
    flutter_secure_storage: ^5.0.2

    # local auth package
    # local_auth: ^0.3.1
    local_auth: ^1.1.10

    # package for slider caruser
    carousel_slider: ^4.0.0

    keyboard_actions: ^3.4.6

    just_audio: ^0.9.20

    #intl: ^0.17.0

    # rxdart: ^0.23.1
    rxdart: ^0.27.3

    permission_handler: ^8.3.0

    draggable_scrollbar: ^0.1.0

    page_transition: ^2.0.5

    cached_network_image: ^3.2.0

    image: ^3.1.1

    image_cropper: ^1.4.1

    # simple_image_crop: ^0.1.3

    webview_flutter: ^2.8.0

    # flutter_full_pdf_viewer: ^1.0.6

    dio: ^4.0.4

    percent_indicator: ^4.0.0

    country_icons: ^2.0.2

    version: ^2.0.0

    shared_preferences: ^2.0.13

    audio_video_progress_bar: ^0.10.0
    just_waveform: ^0.0.2

    # Open file plugin
    open_file: ^3.2.1

    uuid: ^3.0.5

    # A library to draw charts in Flutter
    fl_chart: ^0.41.0

    # Firebase packages.
    #firebase_core: ^1.12.0
    #firebase_messaging: ^11.2.6

    #firebase_crashlytics: ^2.5.0

    #firebase_dynamic_links: ^4.0.5

    cloud_firestore: ^3.1.7

    # Dart-Basic-Utils
    basic_utils: ^4.1.0
    # A Flutter plugin to use the Google Analytics for Firebase API.
    #firebase_analytics: ^9.1.0

    # Facebook tracker
    facebook_app_events: ^0.14.8

    animations: ^2.0.2
    flutter_vibrate: ^1.3.0
    share: ^2.0.4
    characters: ^1.1.0
    flutter_verification_code: ^1.1.2+1
    app_tracking_transparency: ^2.0.2+1
    confetti: ^0.6.0
    pin_code_fields: ^7.3.0
    validators: ^3.0.0
    flutter_phoenix: ^1.0.0

    # used for picking media from device
    file_picker: ^4.3.3

    flutter_app_badger: ^1.3.0

    dropbox_client: ^0.8.0

    flutter_typeahead: ^3.2.4

    collection: ^1.15.0-nullsafety.4
    dart_ipify: ^1.1.1

    custom_pop_up_menu: ^1.2.3+1

    modal_bottom_sheet: ^2.0.0

    launch_review: ^3.0.1

    flutter_slidable: ^1.2.0
    #  flutter_cupertino_date_picker: ^1.0.24

    dotted_border: ^2.0.0+2

    searchfield: ^0.5.6

    simple_autocomplete_formfield: ^0.3.0
    # xml: ^5.3.1

    path_drawing: ^1.0.0
    flutter_native_splash: any
    flutter_launcher_icons: ^0.9.2
    # html: ^0.15.0

    auto_size_text: ^3.0.0

    flutter_html: ^2.2.1
    better_player: ^0.0.81
    timeago: ^3.2.2
    video_compress: ^3.1.0
    flutter_sound: ^9.1.9
    linkwell:
        git:
            url: https://github.com/dj-igroove/linkwell_update.git
            ref: master
    flutter_ffmpeg: ^0.4.2
    video_player: ^2.3.0
    custom_refresh_indicator: ^1.1.1
    flutter_audio_waveforms: ^1.1.1+2
    #audio_waveforms: ^0.1.1
    visibility_detector: ^0.2.2
    firebase_crashlytics: ^2.5.2
    firebase_analytics: ^9.1.1
    firebase_messaging: ^11.2.7
    firebase_dynamic_links: ^4.0.7
    firebase_core: ^1.12.0
    audio_service: 0.18.4
    audio_session: ^0.1.9

dev_dependencies:
    flutter_test:
        sdk: flutter
    lints: ^1.0.1

flutter_icons:
    ios: true
    android: true
    # image_path_ios: "assets/icon_whitelabel_2.png"
    # image_path_android: "assets/icon_whitelabel_2.png"
    image_path_ios: 'assets/icon_igroove.png'
    image_path_android: 'assets/icon_igroove.png'
dependency_overrides:
    photo_view:
        git:
            url: https://github.com/bluefireteam/photo_view
            ref: master
    flutter_svg: ^1.0.0
    firebase_messaging_platform_interface: 3.1.6
    intl: '>=0.17.0'
    # The following adds the Cupertino Icons font to your application.
    # Use with the CupertinoIcons class for iOS style icons.
    cupertino_icons: ^0.1.3
    # provider for state management and dependency injection
    provider: ^6.0.2

    # petitparser: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
    # The following line ensures that the Material Icons font is
    # included with your application, so that you can use the icons in

    # the material Icons class.

    uses-material-design: true

    assets:
        - assets/images/
        - assets/icons/
        - assets/icons/svgs/

    # To add assets to your application, add an assets section, like this:
    # assets:
    #  - images/a_dot_burr.jpeg
    #  - images/a_dot_ham.jpeg

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    fonts:
        - family: Graphik
          fonts:
              - asset: fonts/Graphik-Regular-Web.ttf
                weight: 400
              - asset: fonts/Graphik-Medium-Web.ttf
                weight: 500
              - asset: fonts/Graphik-Semibold-Web.ttf
                weight: 600
        - family: BarlowCondensed
          fonts:
              - asset: fonts/BarlowCondensed-SemiBold.ttf
                weight: 600
        - family: SvgIcons
          fonts:
              - asset: fonts/SvgIcons.ttf

    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
